SELECT OWNER,
SEGMENT_NAME TABLE_NAME,
SEGMENT_TYPE,
ROUND(BYTES/1024,2) TABLE_KB,
NUM_ROWS,
BLOCKS,
EMPTY_BLOCKS,
HWM HIGHWATER_MARK,
AVG_USED_BLOCKS,
GREATEST(ROUND(100 * (NVL(HWM - AVG_USED_BLOCKS,0) /
GREATEST(NVL(HWM,1),1) ),2),0) BLOCK_INEFFICIENCY,
MAX_EXTENT_PCT,
EXTENTS,
MAX_EXTENTS,
DECODE(GREATEST(MAX_FREE_SPACE -
NEXT_EXTENT,0),0,'N','Y') CAN_EXTEND_SPACE,
NEXT_EXTENT,
MAX_FREE_SPACE,
O_TABLESPACE_NAME TABLESPACE_NAME
FROM
(SELECT A.OWNER OWNER,
SEGMENT_NAME,
SEGMENT_TYPE,
BYTES,
NUM_ROWS,
A.BLOCKS BLOCKS,
B.EMPTY_BLOCKS EMPTY_BLOCKS,
A.BLOCKS - B.EMPTY_BLOCKS - 1 HWM,
DECODE(ROUND((B.AVG_ROW_LEN * NUM_ROWS * (1 +
(PCT_FREE/100))) /
C.BLOCKSIZE,0),0,1,ROUND((B.AVG_ROW_LEN * NUM_ROWS *
(1 + (PCT_FREE/100))) / C.BLOCKSIZE,0)) + 2
AVG_USED_BLOCKS,
ROUND(100 * (NVL(B.CHAIN_CNT,0) /
GREATEST(NVL(B.NUM_ROWS,1),1)),2),
A.EXTENTS EXTENTS,
ROUND(100 * (A.EXTENTS / A.MAX_EXTENTS),2) MAX_EXTENT_PCT,
A.MAX_EXTENTS MAX_EXTENTS,
B.NEXT_EXTENT NEXT_EXTENT,
B.TABLESPACE_NAME O_TABLESPACE_NAME
FROM SYS.DBA_SEGMENTS A,
SYS.DBA_INDEXES B,
SYS.TS$ C
WHERE( A.OWNER = B.OWNER ) and
( SEGMENT_NAME = INDEX_NAME ) and
"afiedt.buf" 90 lines, 2428 characters
SYS.DBA_INDEXES B,
SYS.TS$ C
WHERE( A.OWNER = B.OWNER ) and
( SEGMENT_NAME = INDEX_NAME ) and
( ( SEGMENT_TYPE = 'INDEX' ) ) AND
B.TABLESPACE_NAME = C.NAME
UNION ALL
SELECT A.OWNER OWNER,
SEGMENT_NAME || '.' || B.PARTITION_NAME,
SEGMENT_TYPE,
BYTES,
B.NUM_ROWS,
A.BLOCKS BLOCKS,
B.EMPTY_BLOCKS EMPTY_BLOCKS,
A.BLOCKS - B.EMPTY_BLOCKS - 1 HWM,
DECODE(ROUND((B.AVG_ROW_LEN * B.NUM_ROWS * (1 +
(B.PCT_FREE/100))) /
C.BLOCKSIZE,0),0,1,ROUND((B.AVG_ROW_LEN * B.NUM_ROWS *
(1 + (B.PCT_FREE/100))) / C.BLOCKSIZE,0)) + 2
AVG_USED_BLOCKS,
GREATEST(NVL(B.NUM_ROWS,1),1)),2) 
A.EXTENTS EXTENTS,
ROUND(100 * (A.EXTENTS / A.MAX_EXTENTS),2)
MAX_EXTENT_PCT,
A.MAX_EXTENTS MAX_EXTENTS,
B.NEXT_EXTENT,
B.TABLESPACE_NAME O_TABLESPACE_NAME
FROM SYS.DBA_SEGMENTS A,
SYS.DBA_IND_PARTITIONS B,
SYS.TS$ C,
SYS.DBA_INDEXES D
WHERE A.OWNER='POSPROD' AND ( A.OWNER = B.TABLE_OWNER ) and
( SEGMENT_NAME = B.INDEX_NAME ) and
( ( SEGMENT_TYPE = 'INDEX PARTITION' ) ) AND
B.TABLESPACE_NAME = C.NAME AND
B.NUM_ROWS >0 AND
D.OWNER='POSPROD' AND
D.OWNER = B.INDEX_OWNER AND
D.TABLE_NAME = B.INDEX_NAME AND
A.PARTITION_NAME = B.PARTITION_NAME),
( SELECT TABLESPACE_NAME F_TABLESPACE_NAME,MAX(BYTES)
MAX_FREE_SPACE
FROM SYS.DBA_FREE_SPACE
GROUP BY TABLESPACE_NAME)
WHERE F_TABLESPACE_NAME = O_TABLESPACE_NAME AND
GREATEST(ROUND(100 * (NVL(HWM - AVG_USED_BLOCKS,0) /
GREATEST(NVL(HWM,1),1) ),2),0) > 25
ORDER BY 10 DESC, 1 ASC,2 ASC
/